#FROM eclipse-temurin:17-jdk-alpine
#VOLUME /tmp
#COPY ./javams/target/accessing-data-mysql-complete-0.0.1-SNAPSHOT.jar app.jar
#ENTRYPOINT ["java","-jar","/app.jar"]

FROM openjdk:17-jdk-slim
VOLUME /tmp
COPY ./facturacion-backend/target/facturacion-backend-0.0.1-SNAPSHOT.jar facturacion-backend.jar
ENTRYPOINT ["java", "-jar", "/facturacion-backend.jar"]