version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-facturacion
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: facturacion
      MYSQL_USER: facturacionuser
      MYSQL_PASSWORD: facturacionpass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - facturacion-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile-java
    #dockerfile: Dockerfile-java
    container_name: facturacion-backend
    #command: tail -f /dev/null
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-facturacion:3306/facturacion
      - SPRING_DATASOURCE_USERNAME=facturacionuser
      - SPRING_DATASOURCE_PASSWORD=facturacionpass
    depends_on:
      - mysql
    networks:
      - facturacion-network

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - facturacion-network

networks:
  facturacion-network:
    driver: bridge
